### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by bflippedyx** [varunagrawal/VisualQA#2]
--arch DeeperLSTM --batch_size 16
image_embeddings/coco_train_vgg_fc7.pth
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    main()
  File "main.py", line 31, in main
    transforms=transform)
  File "/home/jingbi/VQA/dataset.py", line 31, in get_train_dataloader
    transforms=transforms),
  File "/home/jingbi/VQA/dataset.py", line 79, in __init__
    self.images_dataset = torch.load(images_dataset)
  File "/home/jingbi/.conda/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/jingbi/.conda/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 459, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x0d'.
Makefile:18: recipe for target 'main' failed
make: *** [main] Error 1

I'm trying to train your new version with another arch, but it keep saying this error, no matter how I modified related file, I think you should know.

BTW, it's better to change the data path(~/dataset) in Makefile to (./dataset)

**Comment by varunagrawal** [comment]
I have updated the image embeddings. Can you try again?

**Comment by varunagrawal** [comment]
Any updates on this?

**Comment by gushart** [comment]
hello!I've got the same error
